// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcKxLDZgsRdiAXpUNmTX_--DEpZnEdamE',
    appId: '1:505119047553:web:436d4a9803bce303977280',
    messagingSenderId: '505119047553',
    projectId: 'socialmedia-5ed18',
    authDomain: 'socialmedia-5ed18.firebaseapp.com',
    storageBucket: 'socialmedia-5ed18.firebasestorage.app',
    measurementId: 'G-NEJHPZ7HBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjMdMjIdymlcqPEr9tnT_o-UWWdU8kI1w',
    appId: '1:505119047553:android:c68751f1df4c779c977280',
    messagingSenderId: '505119047553',
    projectId: 'socialmedia-5ed18',
    storageBucket: 'socialmedia-5ed18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaVdltdbkl6pNX2PfOfrv1ZQ1xL7c7w9w',
    appId: '1:505119047553:ios:b5e9df6caa79a95d977280',
    messagingSenderId: '505119047553',
    projectId: 'socialmedia-5ed18',
    storageBucket: 'socialmedia-5ed18.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
